
--EFF_END_DT input table
CREATE VOLATILE MULTISET TABLE "EFF_END_DT" 
  (
     "ISIN_TO_LEI_LEI" CHAR (20) NOT NULL
   , "ISIN" CHAR (12) NOT NULL
   , "EFF_DT" DATE NOT NULL
   , "END_DT" DATE NOT NULL
   , "MPNG_SRC" CHAR (32) NOT NULL
  )
  ON
COMMIT PRESERVE ROWS ;

COMMIT WORK ;

-- NEW RECORDS
CREATE VOLATILE multiset TABLE NEW_RECORDS , NO log AS 
  (  sel ISIN
       , ISIN_TO_LEI_LEI
       , MPNG_SRC
     FROM EFF_END_DT 
     MINUS 
     sel ISIN
       , ISIN_TO_LEI_LEI
       , MPNG_SRC
     FROM EDWCLT_UA4.ISIN_LEI
     WHERE 
        CURRENT_DATE BETWEEN EFF_DT AND END_DT 
    ) WITH DATA ON
COMMIT PRESERVE ROWS ;

-- closing records in TARGET ISIN_LEI table with day-1 date
UPDATE ISIN_LEI
SET END_DT = CURRENT_DATE - 1
WHERE 1 = 1
    AND (ISIN) in (sel ISIN  FROM NEW_RECORDS)
    AND CURRENT_DATE BETWEEN EFF_DT AND END_DT ;

--create table NEW_RECORDS_EFF_END_DT with new records and dates
CREATE VOLATILE multiset TABLE NEW_RECORDS_EFF_END_DT , NO log AS (
  sel ISIN
       , ISIN_TO_LEI_LEI
       , MPNG_SRC
       ,  CURRENT_DATE AS EFF_DT
       , date'2999-12-31' AS END_DT
   FROM NEW_RECORDS
  ) WITH DATA ON
COMMIT PRESERVE ROWS ;

-- insert new record to target table
INSERT INTO ISIN_LEI(ISIN, ISIN_TO_LEI_LEI, MPNG_SRC, EFF_DT, END_DT) sel ISIN
  , ISIN_TO_LEI_LEI
  , MPNG_SRC
  , EFF_DT
  , END_DT
FROM NEW_RECORDS_EFF_END_DT ;


